### ISSUE TITLE
Feature request: allow creating case-sensitive FS

### ISSUE THREAD

**Issue by zxcat** [imothee/tmpdisk#22]
Sometimes we need a case sensitive file system on a RAM-disk. You can create a drive and then format it to "Mac OS Extended (Case-sensitive, Journaled)". It's not difficult, but it kills the spotlight indexing limitation, pre-created folders, and the icon. So all this must be created outside of TmpDisk again.

It would be great if TmpDisk allowed user to set fs format.

**Comment by zxcat** [comment]
There is also a bug: for some reason TmpDisk didn't show created virtual disk in "Current TmpDisks" menu. Just found there was a file named `.tmpdisk`, which disappears after format disk to case sensitive. So it's related to this issue.

**Comment by imothee** [comment]
Hi @zxcat

I went and updated the 2.0.5 alpha release https://github.com/imothee/tmpdisk/releases/tag/v2.0.5-alpha to include two checkboxes for CaseSensitive and Journaled Filesystem selectors.

I was on the fence at exposing the entire DiskUtil filesystem selection system since many users are not that technical (but for example, for compatibility since many users are on old MacOS versions I still use HFS instead of APFS).

I'd love to have you give the 2.0.5 Alpha a whirl and get any feedback on the implementation || filesystem limitations noted above.

<img width="1059" alt="TmpDiskFileSystems" src="https://user-images.githubusercontent.com/574560/215023883-eaa268bc-3a51-4353-9b6a-368baabe13f4.png">
<img width="853" alt="AutoCreateManager" src="https://user-images.githubusercontent.com/574560/215023898-1c868de3-4059-4c1d-aead-b7c2f2c63a4e.png">

**Comment by zxcat** [comment]
wow that was fast!
installed, seems to work perfect.
Bonus: now I can create case sensitive without journal, which was not allowed from Disk Utility.

Thank you!

I'll report if some issue appears.
